apiVersion: v2
name: brokencrystals-exp
description: |
  Benchmark application that uses modern technologies and implements a set of
  common security vulnerabilities
type: application
version: 0.0.52
keywords:
  - brokencrystals-exp
  - brkn-e
